#!/usr/bin/bash

# Colors
RED="\e[1;31m"
BLU="\e[1;34m"
CYA="\e[1;36m"
GRE="\e[1;32m"
YEL="\e[1;33m"
MAG="\e[1;35m"
END="\e[0m"

# Packages
PKGS=$GRE"Packages: "$END
[ $(command -v dpkg) ] && PKGS+="$(dpkg --get-selections | wc -l) (dpkg)"
[ $(command -v rpm) ] && PKGS+="$(rpm -qa | wc -l) (rpm)"
[ $(command -v pacman) ] && PKGS+="$(pacman -Q | wc -l) (pacman)"
[ $(command -v flatpak) ] && PKGS+=" $(flatpak list | wc -l) (flatpak)"
[ $(command -v snap) ] && PKGS+=" $(snap list | wc -l) (snap)"

# Distribution name
OS=$CYA"OS: "$END"$(cat /etc/os-release | grep PRETTY_NAME | cut -d\" -f2)"

# Kernel
KERNEL=$YEL"Kernel: "$END"$(uname -s) $(uname -r)"

# CPU
CPU=$RED"CPU: "$END"$(grep 'model name' /proc/cpuinfo | head -1 | cut -f3- -d" ")"

# GPU
GPU=$MAG"GPU: "$END"$(lspci | grep VGA | head -1 | grep -Po '\[\K[^\]]*')"

# RAM
RAM_TOTAL=$(free -m | head -n 2 | tail -n 1 | tr -s ' ' | cut -d' ' -f 2)
RAM_USED=$(free -m | head -n 2 | tail -n 1 | tr -s ' ' | cut -d' ' -f 3)
RAM=$BLU"RAM: "$END"$RAM_USED / $RAM_TOTAL MB ($(($RAM_USED * 100 / $RAM_TOTAL))%)"

# Information summary
INFO="
$OS
$PKGS
$KERNEL
$CPU
$GPU
$RAM
"

# Logo's
shopt -s nocasematch # Ignore case
if [[ $OS =~ "Arch" ]]; then
LOGO="
$CYA      /\      $END
$CYA     /  \     $END
$CYA    /\   \    $END
$CYA   /  ,,  \   $END
$CYA  /  |  | -\  $END
$CYA /_-'    '-_\ $END"

elif [[ $OS =~ "Fedora" ]]; then
LOGO="
$BLU         ___  $END
$BLU       /  __| $END
$BLU    _ |  |__  $END
$BLU  /  _|  |__| $END
$BLU |  |_|  |    $END
$BLU  \_____/     $END"

elif [[ $OS =~ "Ubuntu" ]]; then
LOGO="
$YEL    ,--(0).   $END
$YEL   / ,---. \  $END
$YEL (0) |   |  | $END
$YEL   \ '---' /  $END
$YEL    '---(0)   $END
$YEL              $END"

elif [[ $OS =~ "Debian" ]]; then
LOGO="
$RED      ____    $END
$RED    /  __ \   $END
$RED   |  / *' |  $END
$RED   |  \___-'  $END
$RED   '_         $END
$RED     '--_     $END"

elif [[ $OS =~ "pop!_OS" ]]; then
LOGO="
$CYA  ____     _  $END
$CYA |     \  | | $END
$CYA | (_)  | | | $END
$CYA |   __/  | | $END
$CYA |  |     '_' $END
$CYA '__'     (_) $END"
fi
# Print logo and info
clear
paste <(echo -e "$LOGO") <(echo -e "$INFO")
